# backend/mappings.py

NAME_MAP = {
    # API-Football Name : CSV Name
    "Bayern Munich": "Bayern Munich",
    "Borussia Dortmund": "Dortmund",
    "RB Leipzig": "RB Leipzig",
    "Union Berlin": "Union Berlin",
    "SC Freiburg": "Freiburg",
    "Bayer 04 Leverkusen": "Leverkusen",
    "Bayer Leverkusen": "Leverkusen",
    "Eintracht Frankfurt": "Eint Frankfurt",
    "VfL Wolfsburg": "Wolfsburg",
    "Mainz 05": "Mainz 05",
    "1. FSV Mainz 05": "Mainz 05",
    "Borussia Monchengladbach": "Gladbach",
    "M'gladbach": "Gladbach",
    "Werder Bremen": "Werder Bremen",
    "TSG 1899 Hoffenheim": "Hoffenheim",
    "TSG Hoffenheim": "Hoffenheim",
    "FC Augsburg": "Augsburg",
    "Augsburg": "Augsburg",
    "VfB Stuttgart": "Stuttgart",
    "VfL Bochum": "Bochum",
    "1. FC Heidenheim": "Heidenheim",
    "Heidenheim": "Heidenheim",
    "Darmstadt 98": "Darmstadt 98",
    "St. Pauli": "St. Pauli",
    "FC St. Pauli": "St. Pauli",
    "Holstein Kiel": "Holstein Kiel",
    "Kiel": "Holstein Kiel",
    "1. FC Koln": "Köln",
    "FC Koln": "Köln",
    "Koln": "Köln",
    "Hertha Berlin": "Hertha BSC",
    "Hertha BSC": "Hertha BSC",
    "Schalke 04": "Schalke 04",
    "FC Schalke 04": "Schalke 04"
}